### ISSUE TITLE
Permission request failed

### ISSUE THREAD

**Issue by wellwhatever** [vvorld/getid-android-sdk#12]
It's impossible now to upload anything from internal storage due to failed permission request. Only happens on Android 13 devices. I guess it's just happens due to new permission rules on Android 13. It now ignores READ_EXTERNAL_STORAGE. So this requested permission that i [found in your manifest](https://github.com/vvorld/getid-android-sdk/blob/v1/app/src/main/AndroidManifest.xml) simply would not work for such devices. Could you please check it?

**Comment by Kiriakovd88** [comment]
The issue with the permission was resolved on April 06, please use newer Android SDK version 2.7.7.

**Comment by semirenko** [comment]
@Kiriakovd88 , are you sure the version 2.7.7 fixes the problem? 
I still see there permissions being asked in manifest file in master branch. 
https://github.com/vvorld/getid-android-sdk/blob/master/app/src/main/AndroidManifest.xml#L11-L12
